Repository missing-semester-tr/missing-semester-tr.github.io, pull requests merged in 2020-06, with the labels that each got.

#17 Translate version-control-2020 lecture to Turkish
  _2020/version-control.md
Labels: translation

#18 Fix typo and improve Turkish translation on version-control-lecture-2020
  _2020/version-control.md
Labels: typo

#20 Add Turkish translation badge next to lectures links
  _2020/command-line.md
  _2020/course-shell.md
  _2020/data-wrangling.md
  _2020/debugging-profiling.md
  _2020/editors.md
  _2020/metaprogramming.md
  _2020/potpourri.md
  _2020/qa.md
  _2020/security.md
  _2020/shell-tools.md
  index.md
Labels: documentations

#21 Translate README.md to Turkish
  README.md
Labels: translation

#22 Add Turkish translation guide to README.md
  README.md
Labels: documentations

#26 Fix typo on version-control-lecture-2020
  _2020/version-control.md
Labels: typo

#27 Translate course-shell-2020 lecture to Turkish
  _2020/course-shell.md
Labels: translation

#31 Translate command-line-environment-2020 lecture to Turkish
  .gitignore
  _2020/command-line.md
Labels: translation
