Repository missing-semester-tr/missing-semester-tr.github.io, pull requests merged in 2020-07, with the labels that each got.

#39 Update lecture's links to the status table
  README.md
Labels: documentations

#28 Translate editors-2020 lecture to Turkish
  _2020/editors.md
Labels: translation

#41 Translate shell-tools-2020 lecture to Turkish
  _2020/shell-tools.md
Labels: translation

#40 Translate metaprogramming-2020 lecture to Turkish
  _2020/metaprogramming.md
Labels: translation

#45 Translate data-wrangling-2020 lecture to Turkish
  _2020/data-wrangling.md
Labels: translation

#49 Fix issue #48 Potpourri sayfasındaki linkler duzeltildi.
  _2020/potpourri.md
Labels: bug
