Repository missing-semester-tr/missing-semester-tr.github.io, pull requests merged in 2020-10, with the labels that each got.

#51 Add 'in the press' section on README.md
  README.md
Labels: documentations

#52 Update gogole analytics tracking id
  _config.yml
Labels: bug

#53 Fixed some markdown issues with links.
  _2020/editors.md
Labels: typo

#54 Fix typo in 2020-data-wrangling.md
  _2020/data-wrangling.md
Labels: typo
